### ISSUE TITLE
Something similar

### ISSUE THREAD

**Issue by szepeviktor** [alleyinteractive/wp-to-psr-4#1]
### Description

Hello! I have something similar growing here

### Use Case

https://github.com/szepeviktor/psr4-rector

**Comment by srtfisher** [comment]
@szepeviktor Is that in a state where I can try it out and use it?

**Comment by szepeviktor** [comment]
Big No.

**Comment by szepeviktor** [comment]
You could try https://github.com/lesphp/psr4-converter
